name: Dummy CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dummy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run dummy step
        run: echo "Dummy check passed."
